version: '3.8'

services:
  knightbot:
    build:
      context: .
      dockerfile: Dockerfile
    image: knightbot
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}