services:
  knightbot:
    build:
      context: .
      dockerfile: Dockerfile
    image: knightbot
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
      - SWIMBOT_DB=${SWIMBOT_DB}
      - COC_TOKEN=${COC_TOKEN}
      - DEBUG=${DEBUG}